### ISSUE TITLE
Not an issue - It's still working flawlessly. 

### ISSUE THREAD

**Issue by Sarah-C** [tedyapo/ten-year-flashlight#3]
Several years on, and my flashlight's still going strong.

It's my main night-time house trip flashlight. I stand it on end on the bedside table to light the room enough to see what my cat's doing, and grab a drink.

It works great for bathroom visits too - any stray household objects show up in the 20 degree beam easily in the depth of night. 

Being green for the eye's sensitivity works for shut eyes too - eyelids filter all the light out, so flashing it around a room at night doesn't wake anyone up.

Knowing it's always there and on, if there's a power cut or otherwise is quite a reassuring thing. =)

**Comment by tedyapo** [comment]
send me your address again and i'll send you a translucent washer. an undocumented upgrade that helps find it at night.

![image](https://user-images.githubusercontent.com/20033344/160641641-2728a9b3-a19b-4b4c-9d4a-c0516e61edb6.png)

**Comment by Sarah-C** [comment]
Did you get my email?

It may have gone into spam. =(
